version: '3.8'

services:
  looki-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: looki-frontend
    ports:
      - "9090:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - looki-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  looki-network:
    driver: bridge

volumes:
  nginx_cache:
    driver: local